package ejemploColas;

import java.awt.Color;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.*;

/**
 *Aplicación en interfaz gráfica que permita simular el funcionamiento 
 * de una cola de cinco posiciones, el programa tendrá tres opciones que son offer,
 * poll y peek, así como una forma de ver el contenido de la cola.
 * @author Cinthia
 */
public class Colas extends javax.swing.JFrame {
    
    private Queue<String> cola;
    private final int MAX = 5;
    private JTextField[] posiciones;  // cuadros de texto de la cola
    private JLabel[] lblFin, lblInicio; // etiquetas móviles

    /**
     * Creates new form Colas
     */
    public Colas() {
        initComponents();
        cola = new LinkedList<>();
        prepararArreglos();
        actualizarCola();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPos1 = new javax.swing.JTextField();
        txtPos2 = new javax.swing.JTextField();
        txtPos3 = new javax.swing.JTextField();
        txtPos4 = new javax.swing.JTextField();
        txtPos5 = new javax.swing.JTextField();
        btnOffer = new javax.swing.JButton();
        btnPoll = new javax.swing.JButton();
        btnPeek = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Funcionamiento de las colas");

        txtPos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPos2ActionPerformed(evt);
            }
        });

        btnOffer.setText("Offer");
        btnOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfferActionPerformed(evt);
            }
        });

        btnPoll.setText("Poll");
        btnPoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPollActionPerformed(evt);
            }
        });

        btnPeek.setText("Peek");
        btnPeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeekActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btnOffer)
                        .addGap(90, 90, 90)
                        .addComponent(btnPoll)
                        .addGap(111, 111, 111)
                        .addComponent(btnPeek))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPos2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txtPos3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(txtPos4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(txtPos5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPos1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPeek)
                    .addComponent(btnPoll)
                    .addComponent(btnOffer))
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     // 🔹 Prepara referencias a los cuadros y etiquetas
    private void prepararArreglos() {
        posiciones = new JTextField[]{txtPos1, txtPos2, txtPos3, txtPos4, txtPos5};

        // Creamos etiquetas dinámicas arriba y abajo
        lblFin = new JLabel[MAX];
        lblInicio = new JLabel[MAX];

        JPanel panel = (JPanel) this.getContentPane();

        for (int i = 0; i < MAX; i++) {
            lblFin[i] = new JLabel(" "); // vacío inicialmente
            lblFin[i].setHorizontalAlignment(SwingConstants.CENTER);
            lblInicio[i] = new JLabel(" ");
            lblInicio[i].setHorizontalAlignment(SwingConstants.CENTER);
            panel.add(lblFin[i]);
            panel.add(lblInicio[i]);
        }

        // Usamos layout absoluto para poder posicionar las etiquetas
        setLayout(null);

        // Ajusta manualmente posiciones de los cuadros
        int startX = 100;  // coordenada x inicial
        int y = 100;       // coordenada y base
        int ancho = 80;    // ancho de cada cuadro
        int separacion = 10;

        for (int i = 0; i < MAX; i++) {
            posiciones[i].setBounds(startX + i * (ancho + separacion), y, ancho, 30);
            lblFin[i].setBounds(startX + i * (ancho + separacion), y - 20, ancho, 20);
            lblInicio[i].setBounds(startX + i * (ancho + separacion), y + 35, ancho, 20);
        }

      
    }
    
     private void actualizarCola() {
         String[] contenido = cola.toArray(new String[0]);

        for (int i = 0; i < MAX; i++) {
            if (i < contenido.length) {
                posiciones[i].setText(contenido[i]);
            } else {
                posiciones[i].setText("");
            }
            lblFin[i].setText(" ");
            lblInicio[i].setText(" ");
        }

        if (!cola.isEmpty()) {
            // Mostrar fin arriba del último elemento
            lblFin[contenido.length - 1].setText("Fin");
            lblFin[contenido.length - 1].setForeground(Color.BLUE);

            // Mostrar inicio debajo del primero
            lblInicio[0].setText("Inicio");
            lblInicio[0].setForeground(Color.RED);
        }
    }

    
    private void btnOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfferActionPerformed
         String valor = txtEntrada.getText().trim();
        if (valor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa un valor para encolar.");
            return;
        }
        if (cola.size() >= MAX) {
            JOptionPane.showMessageDialog(this, "La cola está llena.");
            return;
        }
        cola.offer(valor);
        txtEntrada.setText("");
        actualizarCola();
    }//GEN-LAST:event_btnOfferActionPerformed

    private void btnPollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPollActionPerformed
        
         if (cola.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cola está vacía.");
            return;
        }
        String valor = cola.poll();
        txtEntrada.setText(valor);
        actualizarCola();
        
    }//GEN-LAST:event_btnPollActionPerformed

    private void btnPeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeekActionPerformed
       
           if (cola.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cola está vacía.");
            return;
        }
        txtEntrada.setText(cola.peek());
    }//GEN-LAST:event_btnPeekActionPerformed

    private void txtPos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPos2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         java.awt.EventQueue.invokeLater(() -> new Colas().setVisible(true));
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOffer;
    private javax.swing.JButton btnPeek;
    private javax.swing.JButton btnPoll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtPos1;
    private javax.swing.JTextField txtPos2;
    private javax.swing.JTextField txtPos3;
    private javax.swing.JTextField txtPos4;
    private javax.swing.JTextField txtPos5;
    // End of variables declaration//GEN-END:variables
}
